local_resinos:
  app-name: local-app
  build-triggers:
    - Dockerfile: d760c9b28ce78c6fbc97549b60ca71d097533ef04f57796e47fc4592a2023ccd
  environment: []
destination: /usr/src/app
ignore:
  - .git
  - node_modules/
