local_resinos:
  app-name: local-app
  build-triggers:
    - Dockerfile: 4752218cf3a8572e79d84e0879ca7addf03c50070666f8ac2475bd6b15e49bb6
  environment: []
destination: /usr/src/app
ignore:
  - .git
  - node_modules/
