local_resinos:
  app-name: local-app
  build-triggers:
    - Dockerfile: f63e8e5f0cdedadbdc8658678501634ff11c197177987495fb63ada639aba236
  environment: []
destination: /usr/src/app
ignore:
  - .git
  - node_modules/
