local_resinos:
  app-name: local-app
  build-triggers:
    - Dockerfile: a6668a8b8dc99d1f6465e92d209032842520aeed64a6de8e91108afc2c3fca4c
  environment: []
uuid: 11b01264c93e2ca97f2e72a5d987df75
destination: /usr/src/app
ignore:
  - .git
  - node_modules/
