local_resinos:
  app-name: local-app
  build-triggers:
    - Dockerfile: ccf2210a452c1933dd643f154627f88e9c6b9734e65e941f1a213c2683a3917e
  environment: []
destination: /usr/src/app
ignore:
  - .git
  - node_modules/
